Add :fruitshop.wepy to templates
wepyjs/wepy-templates pull request #34
Opened 2020-07-26 12:37 UTC by hdzattain

2020-07-27 06:51 UTC, Gcaufy requested changes

2020-07-27 06:51 UTC, Gcaufy commented on templates/fruitshop/template/package.json
> +    "wepy": "^1.6.0",
不要使用 1.x 的版本

2020-08-03 02:10 UTC, Gcaufy requested changes
请删除没有用到的文件, ignore 不需要提交 的文件

2020-08-03 02:10 UTC, Gcaufy commented on templates/template/fruitshop/.gitignore
> +weapp
weapp 明明 ignore 了，但是代码还是提交了

2020-08-03 02:10 UTC, Gcaufy commented on templates/template/fruitshop/.wepycache
> +{"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\wepy.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modul
这个文件需要 ignore

2020-08-03 02:10 UTC, Gcaufy commented on templates/template/fruitshop/src/pages/Fruit.wpy
> +      wepy.navigateTo({
这个 api 是正常的吗？

2020-08-03 02:14 UTC, hdzattain commented
api是可以用的，weapp不是运行代码的关键嘛？我觉得是这样，可能ignore文件要修改，请问ignore是如何操作的?
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gcaufy"<notifications@github.com&gt;; 
发送时间: 2020年8月3日(星期一) 上午10:10
收件人: "wepyjs/wepy-templates"<wepy-templates@noreply.github.com&gt;; 
抄送: "牛牛爱吃狼"<709249426@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wepyjs/wepy-templates] Add :fruitshop.wepy to templates (#34)





 
@Gcaufy requested changes on this pull request.
 
请删除没有用到的文件, ignore 不需要提交 的文件

 
In templates/template/fruitshop/.gitignore:
 &gt; @@ -0,0 +1,4 @@ +node_modules +dist +weapp  
weapp 明明 ignore 了，但是代码还是提交了
 
 
In templates/template/fruitshop/.wepycache:
 &gt; @@ -0,0 +1 @@ +{"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\wepy.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy-async-function\\index.js":1487759227000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy-com-toast\\toast.wpy":1488432898000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\app.js":1508932484000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\page.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\component.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\event.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\base.js":1508932484000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\util.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\mixin.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy-async-function\\global.js":1487760749000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\promise-polyfill\\promise.js":1511627065000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\regenerator-runtime\\runtime.js":1493390741000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\native.js":1508932485000}  
这个文件需要 ignore
 
 
In templates/template/fruitshop/src/pages/Fruit.wpy:
 &gt; +      this.FruitList[Index].buy_num--; +      this.FruitList[Index].number++; +      this.sum = this.sum - this.FruitList[Index].price; +    }, + +    // 增加数量 +    increase(Index) { +      //console.log(Index); +      this.FruitList[Index].buy_num++; +      this.FruitList[Index].number--; +      this.sum = this.sum + this.FruitList[Index].price; + +    }, + +    goNext() { +      wepy.navigateTo({  
这个 api 是正常的吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-03 02:15 UTC, hdzattain commented on templates/template/fruitshop/.wepycache
> +{"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\wepy.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modul
是要重新pr吗

2020-08-03 02:16 UTC, hdzattain commented on templates/template/fruitshop/.wepycache
> +{"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modules\\wepy\\lib\\wepy.js":1508932485000,"E:\\code\\mine\\js\\wepy_group\\wepy_templates\\templates\\standard\\node_modul
有没办法直接在github里面ignore

2020-08-03 02:16 UTC, hdzattain commented on templates/template/fruitshop/src/pages/Fruit.wpy
> +      wepy.navigateTo({
可以跳转页面

2020-08-03 05:10 UTC, hdzattain commented
no need for further applicaitoin

2020-08-03 05:10 UTC, closed without merging